### PR TITLE
Feat/text utilities and lists

### PR DESCRIPTION
**Pull request by tonymike99**
Added text and list features

https://practical-jennings-877d51.netlify.app/docs.html

### CODE REVIEW

**Review by Omkar-Ghate — APPROVED** [review]
Looks good to me.

**Review by bhushannaikaroskar — APPROVED** [review]
Good to merge. I would suggest to create class file and use that class for iframe rather than declaring same style inside iframe again and again.

**Comment by tonymike99** [comment]
> Good to merge. I would suggest to create class file and use that class for iframe rather than declaring same style inside iframe again and again.

Thanks for reviewing, Bhushan! 
The thing is I copy-pasted the carbon iframe code. I didn't give any styles to it. They come by default. 
I hope it's fine.

**Comment by tonymike99** [comment]
> Looks good to me.

Thanks for reviewing, Omkar!

**Pull request merged**
