### PR TITLE
Feat/image and input

### PR DESCRIPTION
**Pull request by tonymike99**
I've added the image and input component.

https://trusting-wiles-51facb.netlify.app/

### CODE REVIEW

**Review by bhushannaikaroskar — APPROVED** [review]
All good. I hope that comments in html files are added for your convenience if not please better remove them.

**Comment by itsmebipul00** [comment]
Clean, nice work, consider using rems more and specify font sizes

**Comment by tonymike99** [comment]
> All good. I hope that comments in html files are added for your convenience if not please better remove them.

Yes Bhushan. The comments are just for my reference. I will remove them once I finish the CL with docs.

**Review by zoef-yt — APPROVED** [review]
Good to merge. Make sure you removed extra comment afterwards

**Pull request merged**
